spring:
  application:
    name: rest-springboot-java
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_springboot_java?useTimezone=true&serverTimezone=UTC
    username: root
    password: vFPkldYIMM19eNj/Egr0SHxtKQodQtDF
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
    show-sql: false
    open-in-view: false
logging:
  level:
#    root: WARN
    com.abnerkaizer.rest_springboot_java: DEBUG